[workspace]
members = ["program", "script"]
resolver = "2"

[patch.crates-io]
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-v0.10.8" }
sp1-verifier = { path = "sp1-verifier-patch" }
